### PR TITLE
feat: support multiple platforms

### LINKED ISSUE #43: feat: support multiple architectures
Hello,

I would love to see more available architectures for this image (e.g. `linux/arm64`).
Currently there seems to be only [`amd64`](https://quay.io/repository/aminvakil/alpine-ftp-server-tls/manifest/sha256:3a582efd756f5d13674a6544dee46d711673cee85bf31ad8c97457f8a50e1578) available.

### PR DESCRIPTION
**Pull request by fty4**
Add support for building image for multiple platforms.

closes #43

### Manifests at quay

Following screenshot shows new manifests available.

_52.. tag is a push with the PR changes (386, amd64, arm64, ppc64le)
46.. tag is main push without the PR changes (only amd64)_

image

### CODE REVIEW

**Comment by aminvakil** [comment]
I think docker/setup-qemu-action@v3 should be used prior to pushing as well.

**Comment by aminvakil** [comment]
Please rebase with master to fix the trivy step error.

**Comment by fty4** [comment]
> I think docker/setup-qemu-action@v3 should be used prior to pushing as well.

The image builded without qemu in my [test](https://github.com/fty4/aminvakil_docker-alpine-ftp-server-tls/actions/runs/11815223535). If you want I can add it to the workflow anyway.

I've rebased the branch and my check was successfull - you need to trigger the workflow here again.

**Comment by aminvakil** [comment]
You've added a merge commit instead of rebasing, I've fixed it and force-pushed.

**Review by aminvakil — APPROVED** [review]

**Comment by aminvakil** [comment]
Thanks for doing this, please add this to README later on when you've found time.

**Comment by fty4** [comment]
You are right. I am more used to merge into a PR and squash everything in my repos to ensure the history will not change.

Thank you!

**Comment by fty4** [comment]
> Thanks for doing this, please add this to README later on when you've found time.

What do you want me to add to the README?

**Comment by aminvakil** [comment]
> > Thanks for doing this, please add this to README later on when you've found time.
> 
> What do you want me to add to the README?

That this image is available in multiple platforms.

**Comment by fty4** [comment]
Added a new PR - hope this finds you well how I added the information.

After merging that could you trigger a release to get a multi platform image?

**Comment by aminvakil** [comment]
Done in https://github.com/aminvakil/docker-alpine-ftp-server-tls/releases/tag/v3.0.5-r2-16 .

Thank you for this!

**Pull request merged**
